In [3]:
import numpy as np 
from scipy.stats import norm
from scipy.stats import t
import math
from time import time as TIME

### Task 1

In [4]:
def H(theta, y, a, gamma):
    ind = (y >= theta).astype(int)
    val = 1.0 -  ind / (1-a) + 2 * gamma * theta
    return val

def single_asset(a_hat, mu, sigma, dist, df):

    N = 100
    n = 10 ** 6
    l = 10 ** (-4)
    beta = 10 ** 8
    gamma = 10 ** (-8)

    if dist == 'norm':
        y = norm.rvs(loc = mu, scale = sigma, size = (n, N)) #data
    elif dist == 't':
        y = t.rvs(df = df, size = (n,N) ) #data
    ksi = norm.rvs(loc = 0, scale = 1, size = (n, N)) #noise

    theta_old = np.zeros(N)

    for i in range(n):
        theta_new = theta_old - l * H(theta_old, y[i], a_hat, gamma) + ksi[i] * (2 * l / beta) ** 0.5
        theta_old = theta_new

    V = np.mean( np.maximum( y.T - theta_new.reshape(N, -1), 0), 1) / (1-a_hat) + theta_new


    return theta_new, V

In [7]:
start = TIME()
VaR_n_arr1, CVaR_n_arr1 = single_asset(0.95, 0, 1, 'norm', 0)
VaR_n_arr2, CVaR_n_arr2 = single_asset(0.95, 1, 2, 'norm', 0)
VaR_n_arr3, CVaR_n_arr3 = single_asset(0.95, 3, 5, 'norm', 0)
VaR_n_arr11, CVaR_n_arr11 = single_asset(0.99, 0, 1, 'norm', 0)
VaR_n_arr22, CVaR_n_arr22 = single_asset(0.99, 1, 2, 'norm', 0)
VaR_n_arr33, CVaR_n_arr33 = single_asset(0.99, 3, 5, 'norm', 0)
end = TIME()
print('execution time in sec,', end - start)

execution time in sec, 87.85585713386536


In [52]:
start = TIME()
VaR_t_arr1, CVaR_t_arr1 = single_asset(0.95, 0, 0, 't', 10)
VaR_t_arr2, CVaR_t_arr2 = single_asset(0.95, 0, 0, 't', 7)
VaR_t_arr3, CVaR_t_arr3 = single_asset(0.95, 0, 0, 't', 3)
VaR_t_arr11, CVaR_t_arr11 = single_asset(0.99, 0, 0, 't', 10)
VaR_t_arr22, CVaR_t_arr22 = single_asset(0.99, 0, 0, 't', 7)
VaR_t_arr33, CVaR_t_arr33 = single_asset(0.99, 0, 0, 't', 3)
end = TIME()
print('execution time in sec,', end - start)

execution time in sec, 128.31898641586304


In [32]:
print('----------------------------------------q_hat = 0.95----------------------------------------')
print('mu = 0, std = 1', ';','VaR*',  "{:.4f}".format(1.645), ';', 'CVaR*', "{:.4f}".format(2.062), ';','VaR_SGLD', "{:.4f}".format(np.mean(VaR_n_arr1)), '(',"{:.3f}".format(np.std(VaR_n_arr1)), ')', ';', 'CVaR_SGLD', "{:.4f}".format(np.mean(CVaR_n_arr1)), '(',"{:.4f}".format(np.std(CVaR_n_arr1)), ')')
print('mu = 1, std = 2', ';','VaR*', "{:.4f}".format(4.290), ';','CVaR*', "{:.4f}".format(5.124), ';','VaR_SGLD', "{:.4f}".format(np.mean(VaR_n_arr2)), '(',"{:.3f}".format(np.std(VaR_n_arr2)), ')',  ';','CVaR_SGLD', "{:.4f}".format(np.mean(CVaR_n_arr2)), '(',"{:.4f}".format(np.std(CVaR_n_arr2)), ')')
print('mu = 3, std = 5', ';','VaR*', 11.224, ';','CVaR*', 13.311, ';','VaR_SGLD', "{:.3f}".format(np.mean(VaR_n_arr3)), '(',"{:.3f}".format(np.std(VaR_n_arr3)), ')',  ';','CVaR_SGLD', "{:.3f}".format(np.mean(CVaR_n_arr3)), '(',"{:.4f}".format(np.std(CVaR_n_arr3)), ')')
print('\n')
print('----------------------------------------q_hat = 0.99----------------------------------------')
print('mu = 0, std = 1', ';', 'VaR*', "{:.4f}".format(2.236), ';', 'CVaR*', "{:.4f}".format(2.677), ';','VaR_SGLD', "{:.4f}".format(np.mean(VaR_n_arr11)), '(',"{:.3f}".format(np.std(VaR_n_arr11)), ')', ';','CVaR_SGLD', "{:.4f}".format(np.mean(CVaR_n_arr11)), '(',"{:.4f}".format(np.std(CVaR_n_arr11)), ')')
print('mu = 1, std = 2', ';', 'VaR*', "{:.4f}".format(5.653), ';', 'CVaR*', "{:.4f}".format(6.335), ';','VaR_SGLD', "{:.4f}".format(np.mean(VaR_n_arr22)), '(',"{:.3f}".format(np.std(VaR_n_arr22)), ')',  ';', 'CVaR_SGLD', "{:.4f}".format(np.mean(CVaR_n_arr22)), '(',"{:.4f}".format(np.std(CVaR_n_arr22)), ')')
print('mu = 3, std = 5', ';', 'VaR*', 14.623, ';', 'CVaR*', 16.337, ';','VaR_SGLD', "{:.3f}".format(np.mean(VaR_n_arr3)), '(',"{:.3f}".format(np.std(VaR_n_arr33)), ')',  ';','CVaR_SGLD', "{:.3f}".format(np.mean(CVaR_n_arr33)), '(',"{:.4f}".format(np.std(CVaR_n_arr33)), ')')

----------------------------------------q_hat = 0.95----------------------------------------
mu = 0, std = 1 ; VaR* 1.6450 ; CVaR* 2.0620 ; VaR_SGLD 1.6453 ( 0.021 ) ; CVaR_SGLD 2.0632 ( 0.0027 )
mu = 1, std = 2 ; VaR* 4.2900 ; CVaR* 5.1240 ; VaR_SGLD 4.2934 ( 0.031 ) ; CVaR_SGLD 5.1259 ( 0.0047 )
mu = 3, std = 5 ; VaR* 11.224 ; CVaR* 13.311 ; VaR_SGLD 11.227 ( 0.043 ) ; CVaR_SGLD 13.315 ( 0.0102 )


----------------------------------------q_hat = 0.99----------------------------------------
mu = 0, std = 1 ; VaR* 2.2360 ; CVaR* 2.6770 ; VaR_SGLD 2.3304 ( 0.043 ) ; CVaR_SGLD 2.6672 ( 0.0053 )
mu = 1, std = 2 ; VaR* 5.6530 ; CVaR* 6.3350 ; VaR_SGLD 5.6549 ( 0.059 ) ; CVaR_SGLD 6.3318 ( 0.0107 )
mu = 3, std = 5 ; VaR* 14.623 ; CVaR* 16.337 ; VaR_SGLD 11.227 ( 0.101 ) ; CVaR_SGLD 16.330 ( 0.0228 )


In [54]:
print('----------------------------------------q_hat = 0.95----------------------------------------')
print('df = 10', ';','VaR*',  "{:.3f}".format(1.812), ';', 'CVaR*', "{:.3f}".format(2.416), ';','VaR_SGLD', "{:.3f}".format(np.mean(VaR_t_arr1)), '(',"{:.3f}".format(np.std(VaR_t_arr1)), ')', ';', 'CVaR_SGLD', "{:.3f}".format(np.mean(CVaR_t_arr1)), '(',"{:.4f}".format(np.std(CVaR_t_arr1)), ')')
print('df = 7 ', ';','VaR*', "{:.3f}".format(1.895), ';','CVaR*', "{:.3f}".format(2.595), ';','VaR_SGLD', "{:.3f}".format(np.mean(VaR_t_arr2)), '(',"{:.3f}".format(np.std(VaR_t_arr2)), ')',  ';','CVaR_SGLD', "{:.3f}".format(np.mean(CVaR_t_arr2)), '(',"{:.4f}".format(np.std(CVaR_t_arr2)), ')')
print('df = 3 ', ';','VaR*', 2.353, ';','CVaR*', 3.876, ';','VaR_SGLD', "{:.3f}".format(np.mean(VaR_t_arr3)), '(',"{:.3f}".format(np.std(VaR_t_arr3)), ')',  ';','CVaR_SGLD', "{:.3f}".format(np.mean(CVaR_t_arr3)), '(',"{:.4f}".format(np.std(CVaR_t_arr3)), ')')
print('\n')
print('----------------------------------------q_hat = 0.99----------------------------------------')
print('df = 10', ';', 'VaR*', "{:.3f}".format(2.764), ';', 'CVaR*', "{:.3f}".format(3.357), ';','VaR_SGLD', "{:.3f}".format(np.mean(VaR_t_arr11)), '(',"{:.3f}".format(np.std(VaR_t_arr11)), ')', ';','CVaR_SGLD', "{:.3f}".format(np.mean(CVaR_t_arr11)), '(',"{:.4f}".format(np.std(CVaR_t_arr11)), ')')
print('df = 7 ', ';', 'VaR*', "{:.3f}".format(2.998), ';', 'CVaR*', "{:.3f}".format(3.757), ';','VaR_SGLD', "{:.3f}".format(np.mean(VaR_t_arr22)), '(',"{:.3f}".format(np.std(VaR_t_arr22)), ')',  ';', 'CVaR_SGLD', "{:.3f}".format(np.mean(CVaR_t_arr22)), '(',"{:.4f}".format(np.std(CVaR_t_arr22)), ')')
print('df = 3 ', ';', 'VaR*', 4.541, ';', 'CVaR*', 6.968, ';','VaR_SGLD', "{:.3f}".format(np.mean(VaR_t_arr33)), '(',"{:.3f}".format(np.std(VaR_t_arr33)), ')',  ';','CVaR_SGLD', "{:.3f}".format(np.mean(CVaR_t_arr33)), '(',"{:.4f}".format(np.std(CVaR_t_arr33)), ')')

----------------------------------------q_hat = 0.95----------------------------------------
df = 10 ; VaR* 1.812 ; CVaR* 2.416 ; VaR_SGLD 1.810 ( 0.022 ) ; CVaR_SGLD 2.409 ( 0.0037 )
df = 7  ; VaR* 1.895 ; CVaR* 2.595 ; VaR_SGLD 1.900 ( 0.023 ) ; CVaR_SGLD 2.596 ( 0.0042 )
df = 3  ; VaR* 2.353 ; CVaR* 3.876 ; VaR_SGLD 2.354 ( 0.030 ) ; CVaR_SGLD 3.874 ( 0.0149 )


----------------------------------------q_hat = 0.99----------------------------------------
df = 10 ; VaR* 2.764 ; CVaR* 3.357 ; VaR_SGLD 2.763 ( 0.048 ) ; CVaR_SGLD 3.365 ( 0.0098 )
df = 7  ; VaR* 2.998 ; CVaR* 3.757 ; VaR_SGLD 3.003 ( 0.058 ) ; CVaR_SGLD 3.770 ( 0.0119 )
df = 3  ; VaR* 4.541 ; CVaR* 6.968 ; VaR_SGLD 4.533 ( 0.103 ) ; CVaR_SGLD 7.006 ( 0.0427 )


### Task 2

In [4]:
def weight(W):
    val = np.exp(W) / np.sum(np.exp(W))
    return val

def H1(theta, y, W, gamma):
    a_hat = 0.95
    indicator = 1.0 if np.sum(weight(W) * y) >= theta else 0.0 #(np.sum(Weight(W) * y) >= theta).astype(int)
    
    val1 = 1.0 - 1.0 / (1.0 - a_hat) * indicator + 2.0 * gamma * theta #number
    
    L = len(W)
    H = np.zeros(L)
    for j in range(L):
        g_hat = 0
        
        for i in range(L):
            if i == j:
                der = np.exp(W[j]) * np.sum(np.exp(np.delete(W,j))) / (np.sum(np.exp(W))) ** 2
            else:
                der = -np.exp(W[i]) * np.exp(W[j]) / (np.sum(np.exp(W))) ** 2
            g_hat += y[i] * der
            
        H[j] = 1.0 / (1.0 - a_hat) * indicator * g_hat + 2.0 * gamma * W[j]
    return np.insert(H, 0, val1)

def ref_val(y):
    N = 100
    w = np.linspace(0, 1, N)
    res = 10 ** 8
    for i in range(N):
        w1 = w[i]
        for j in range(N):
            w2 = w[j]
            w3 = 1.0 - w1 - w2

            portfolio_LP = w1 * y[0] + w2 * y[1] + w3 * y[2]

            VaR = np.quantile(portfolio_LP, 0.95)
            CVaR = np.mean(portfolio_LP[portfolio_LP >= VaR])

            if CVaR <= res:
                res = CVaR
                res_arr = [w1, w2, w3, VaR, CVaR]
    return res_arr


In [5]:
def multi_assets(params):
    mu1, var1, mu2, var2, mu3, var3 = params

    n = 10 ** 6
    l = 10 ** (-4)
    beta = 10 ** 8
    gamma = 10 ** (-8)
    a_hat = 0.95
    m = 3 #assets number

    y1 = norm.rvs(loc = mu1, scale = var1**0.5, size = n) #data 1st asset
    y2 = norm.rvs(loc = mu2, scale = var2**0.5, size = n) #data 2st asset
    y3 = norm.rvs(loc = mu3, scale = var3**0.5, size = n) #data 3st asset
    y = np.array([y1, y2, y3])
    y_T = y.T
    ksi = norm.rvs(loc = 0, scale = 1, size = (n, m+1)) #noise

    theta_old = np.zeros(m+1)

    for i in range(n):
        theta_new = theta_old - l * H1(theta_old[0], y_T[i], theta_old[1:], gamma) + ksi[i] * (2 * l / beta) ** 0.5
        theta_old = theta_new

    V = np.mean(np.maximum(weight(theta_new[1:]) @ y - theta_new[0], 0)) / (1-a_hat) + theta_new[0]

    return weight(theta_new[1:]), theta_new[0], V, ref_val(y)

In [13]:
start = TIME()
res = multi_assets([500, 1, 0, 10**6, 0, 10**-4])
print(res[:-1])
print(res[-1])
end = TIME()
print(end - start)

(array([6.95073828e-06, 3.01745692e-06, 9.99990032e-01]), 0.02343955384217421, 0.025679992040724478)
[0.0, 0.0, 1.0, 0.016449095894498177, 0.020637334524107206]
94.90452909469604


In [16]:
start = TIME()
res = multi_assets([500, 1, 0, 10**6, 0, 1])
print(res[:-1])
print(res[-1])
end = TIME()
print(end - start)

(array([8.64348681e-06, 1.94437794e-05, 9.99971913e-01]), 1.6647200245358602, 2.0685504923752407)
[0.0, 0.0, 1.0, 1.6473975706496953, 2.063613538535911]
93.98094010353088


In [6]:
start = TIME()
res = multi_assets([0, 10**3, 0, 1, 0, 4])
print(res[:-1])
print(res[-1])
end = TIME()
print(end - start)

(array([0.00156756, 0.79619441, 0.20223803]), 1.4472968061387834)
1.8426126284193736
48.97334027290344


In [ ]:
res = multi_assets([0, 10**3, 0, 1, 0, 4])

In [1]:
res[0]

NameError: name 'res' is not defined

In [2]:
np.sum([1,2])

NameError: name 'np' is not defined

In [47]:
sum(res[-2][:3])

1.0067114093959733

In [37]:
res[2]

1.8484435849909215

In [38]:
res[-2][-1]

4.111616324698849

In [40]:
res[-1]

3

In [41]:
y = res[-1]
w1,w2,w3 = res[-2][:3]
portfolio_LP = w1 * y[0] + w2 * y[1] + w3 * y[2]

VaR = np.quantile(portfolio_LP, 0.95)
CVaR = np.mean(portfolio_LP[portfolio_LP >= VaR])

In [42]:
CVaR

4.111616324698852

In [43]:
y = res[-1]
w1,w2,w3 = res[0]
portfolio_LP = w1 * y[0] + w2 * y[1] + w3 * y[2]

VaR = np.quantile(portfolio_LP, 0.95)
CVaR = np.mean(portfolio_LP[portfolio_LP >= VaR])

In [44]:
CVaR

1.8483135292831983

In [45]:
res[0]

array([0.0015349 , 0.79823866, 0.20022644])

In [46]:
VaR

1.472121942184292

In [ ]:
y1 = norm.rvs(loc = mu1, scale = var1**0.5, size = n) #data 1st asset
y2 = norm.rvs(loc = mu2, scale = var2**0.5, size = n) #data 2st asset
y3 = norm.rvs(loc = mu3, scale = var3**0.5, size = n) #data 3st asset